<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>

    <style>
.select { 
    background: -moz-linear-gradient(top, #c8ffc4, #afb8ff); 
    background: -ms-linear-gradient(top, #c8ffc4, #afb8ff); 
    background: -webkit-linear-gradient(top, #c8ffc4, #afb8ff); 
    background: linear-gradient(top, #c8ffc4, #afb8ff); 
    border: 2px solid #999; 
    border-radius: 3px; 
    box-shadow: 0 0 5px #999; 
    color: #111; 
    font-size: 15px; 
    padding: 10px; 
    padding-right: 20px
    width: 200px; 
    
  }
  .column{
    margin-top: 10px;
}
    </style>
</head> 
  <header class="position">
        <div class="navigation">   
            <nav>
                <a href="main.php"> Главная</a>
                <a href="#" >Список товаров</a>
            </nav>
        </div>
    </header>
<body onload="myFunction()">


